### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by Cluab** [Cluab/Book-An-Appointment-Back-End#21]
#### Team Members : 5

![Kanban_Board_snapshot](https://user-images.githubusercontent.com/40334904/228784664-1cedd355-93eb-413e-8371-0ee1c8c1af21.png)
 ### [Link To the KanBan Board](https://github.com/Cluab/Book-An-Appointment-Back-End/projects/1)

**Comment by Meltrust** [comment]
Hi STUDENT_MENTION 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not include a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi @Meltrust ,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

### Well done!





Congratulations! 🎉 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by manq2010** [comment]
![Screenshot from 2023-04-01 15-31-16](https://user-images.githubusercontent.com/53082877/229292065-d00875c9-8184-4f4b-a9a3-f223d7e32ae6.png)

**Comment by Cluab** [comment]
![image](https://user-images.githubusercontent.com/103601335/229704754-dff3a87a-d7a7-44da-8da8-e3f4bf8896a0.png)

**Comment by manq2010** [comment]
![image](https://user-images.githubusercontent.com/53082877/229860994-cdd35fca-81f4-4fd5-a475-32efdc6b343c.png)

**Comment by Cluab** [comment]
![image](https://user-images.githubusercontent.com/103601335/230130203-d37abc65-183f-4fd5-998f-5a5b6028c238.png)

**Comment by manq2010** [comment]
![image](https://user-images.githubusercontent.com/53082877/230485198-4983c57c-6329-4714-88ec-e3ee38de0d43.png)

**Comment by Cluab** [comment]
![image](https://user-images.githubusercontent.com/103601335/230621611-704b774c-5804-4fb1-8984-2c53a196a912.png)

**Comment by Cluab** [comment]
![image](https://user-images.githubusercontent.com/103601335/230779596-9b9c44c5-c1b6-4a54-b054-6bd5f43e7611.png)

**Comment by Cluab** [comment]
![image](https://user-images.githubusercontent.com/103601335/231219893-2974e418-db7a-46d3-92b4-b78bfe980de0.png)

**Comment by manq2010** [comment]
![image](https://user-images.githubusercontent.com/53082877/231412356-c34a9bfb-174d-45d5-b1a7-66a5b5e917be.png)

**Comment by manq2010** [comment]
![image](https://user-images.githubusercontent.com/53082877/231566713-084bb10c-cddd-41f6-9be2-679010613c47.png)
